version: 2.0

phases:
  install:
    runtime_versions:
      nodejs: 8
    commands:
      - echo Installing serverless framework...
      - npm i -g serverless
  pre_build:
    commands:
      -
  build:
    commands:
      - echo Deployment started on `date`
      # put build command for layers here
      - cd layers
      - aws cloudformation package --template-file layers.yaml --output-template-file layers.cf.yaml --s3-bucket $STACK_BUCKET
      - aws cloudformation deploy --template-file layers.cf.yaml --stack-name bliss-layers
      - cd ..
  post_build:
    commands:
      - echo Deployment done on `date`
