version: 0.2

# environment variable/s used (code build environment variables)
# STACK_BUCKET - name of s3 bucket used as cloudformation stack repo
# STACK_NAME - name for this cloudformation stack; <company name>-bliss-layers

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      -
  pre_build:
    commands:
      -
  build:
    commands:
      - echo Deployment started on `date`
      - cd layers
      - aws cloudformation package --template-file layers.yaml --output-template-file layers.cf.yaml --s3-bucket $STACK_BUCKET
      - aws cloudformation deploy --template-file layers.cf.yaml --stack-name $STACK_NAME
  post_build:
    commands:
      - echo Deployment done on `date`
