AWSTemplateFormatVersion: 2010-09-09
Description: Parameter Store creation for EProducts

Parameters:
  CompanyNameParam:
    Type: String
    Description: Full/abbreviated name of the company using this E-Products instance
  DatabaseHostParam:
    Type: String
    Description: String defining the host path for the E-Products database
  DatabasePortParam:
    Type: String
    Description: String defining the port set used by the E-Products database

Resources:
  DatabaseHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /bliss/${CompanyName}/db/host
          - { CompanyName: !Ref CompanyNameParam }
      Type: "String"
      Value:
        Ref: DatabaseHostParam
      Description: "MySQL database host name for E Products"
      Tier: Standard
  DatabasePort:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /bliss/${CompanyName}/db/port
          - { CompanyName: !Ref CompanyNameParam }
      Type: "String"
      Value:
        Ref: DatabasePortParam
      Description: "MySQL database port for E Products"
      Tier: "Standard"
  DatabaseNameCTPL:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /bliss/${CompanyName}/db/ctpl/database
          - { CompanyName: !Ref CompanyNameParam }
      Type: "String"
      Value: ctpl
      Description: "MySQL database used for ECTPL for E Products"
      Tier: "Standard"
  DatabaseNameTravel:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub:
          - /bliss/${CompanyName}/db/travel/database
          - { CompanyName: !Ref CompanyNameParam }
      Type: "String"
      Value: travel
      Description: "MySQL database used for Travel for E Products"
      Tier: "Standard"
