DROP VIEW IF EXISTS MC_VEHICLE_INFO;

CREATE VIEW MC_VEHICLE_INFO AS
SELECT a.MODEL_YEAR, a.MAKE_CD, c.MAKE, c.CAR_COMPANY_CD, b.CAR_COMPANY, a.SERIES_CD,
	   d.ENGINE_SERIES, a.REG_TYPE, a.MOTOR_NO, a.SERIAL_NO, a.PLATE_NO, a.COC_SERIAL_NO,
       a.COC_ATCN, a.COLOR, a.MV_FILE_NO, a.MV_TYPE_CD, a.MV_PREM_TYPE_CD, a.ASSIGNEE,
       a.MOT_TYPE, a.UNLADEN_WT, a.NO_OF_PASS, a.COC_NO, a.POLICY_ID
  FROM EPIT_CTPL_VEHICLE a  
  JOIN EPIM_MC_CAR_COMPANY b ON a.CAR_COMPANY_CD = b.CAR_COMPANY_CD
  JOIN EPIM_MC_MAKE c ON a.MAKE_CD = c.MAKE_CD AND a.CAR_COMPANY_CD = c.CAR_COMPANY_CD
  JOIN EPIM_MC_ENG_SERIES d ON a.SERIES_CD = d.SERIES_CD AND a.CAR_COMPANY_CD = d.CAR_COMPANY_CD AND a.MAKE_CD = d.MAKE_CD;
  