CREATE TABLE EPIT_CTPL_VEHICLE (
	POLICY_ID			bigint(12) 		not null comment 'Unique identification of the transaction.',
    MOTOR_NO			varchar(30)		not null comment 'Engine/Motor Number of the vehicle.',
	PLATE_NO			varchar(10)		not null comment 'Plate Number of the vehicle.',
	SERIAL_NO			varchar(25)		not null comment 'Chassis Serial Number of the vehicle.',
	MV_FILE_NO			varchar(15)		not null comment 'MV File Number of the vehicle.',
	MODEL_YEAR			varchar(4)		not null comment 'Year model of the vehicle.',
	REG_TYPE			varchar(1)		not null comment 'CTPL Registration Type: N – New,  R – Renewal',
	MV_TYPE_CD			varchar(2)		not null comment 'Type of vehicle insured.',
	MV_PREM_TYPE_CD		varchar(2)		not null comment 'Premium Type Code.',
	CAR_COMPANY_CD		bigint(6)		not null comment 'Code used to identify the Car Company name.',
	MAKE_CD				bigint(12)		not null comment 'Make of the vehicle.',
	SERIES_CD			bigint(12)		not null comment 'It is the code used to identify the Engine Series of the vehicle.',
	MOT_TYPE			int(2)			not null comment 'It is the code used to identify the specific Motor Type.',
	UNLADEN_WT			varchar(20)		not null comment 'Contains the Unladen Weight of the motor type.',
    NO_OF_PASS			int(3)			comment 'Number of passengers.',
    COLOR				varchar(50) 	not null comment 'Color of the vehicle.',
	ASSIGNEE			varchar(30)		comment 'Assignee of the vehicle.',
    COC_SERIAL_NO		bigint(7)		not null comment 'COC Serial Number of the vehicle.',
	COC_NO				varchar(10)		comment 'Assigned Certificate of Cover number to the vehicle.',
	COC_ATCN			varchar(12)		comment 'COCAF Authentication Number of the vehicle.',
	LAST_UPDATE			datetime		not null comment 'Date when the record is last updated. This is system generated.',
    primary key (POLICY_ID)
);