CREATE TABLE EPIT_CTPL_POLBASIC (
	POLICY_ID			bigint(12) 		not null auto_increment comment 'Unique identification of the transaction.',
    LINE_CD				varchar(2)		not null comment 'Line code used for CTPL policies.',
    SUBLINE_CD			varchar(7)		not null comment 'Subline code used to identify the type of CTPL policies.',
    ISS_CD				varchar(2)		not null comment 'Issuing Source for CTPL policies.',
    ISSUE_DATE			datetime		not null comment 'CTPL issue date using the format ‘YYYY-MM-DD’.',
    INCEPTION_DATE		datetime		not null comment 'CTPL inception date using the format ‘YYYY-MM-DD’.',
    EXPIRY_DATE			datetime		not null comment 'CTPL expiry date using the format ‘YYYY-MM-DD’.',
    FIRST_NAME			varchar(250)	comment 'First Name of the Insured.',
    LAST_NAME			varchar(250)	comment 'Last Name of the Insured.',
    MIDDLE_INITIAL		varchar(2)		comment 'Middle Initial of the Insured.',
    DOB					datetime		comment 'Date of Birth of the Insured.',
    GENDER				varchar(1)		comment 'Gender of the Insured.',
    EMAIL_ADD			varchar(100)	not null comment 'Email address of the Insured.',
    ADDRESS				varchar(150)	comment 'Mailing address of the Insured.',
    ZIP_CD				varchar(12)		not null comment 'ZIP Code of the Insured',
    PHONE_NO			varchar(40)		not null comment 'Contact Number of the Insured.',
    TIN_NO				varchar(15)		not null comment 'Tax identification number of the Insured.',
    CORPORATE_TAG		varchar(1)		not null comment 'Tag to identify whether the assured is an INDIVIDUAL type or a CORPORATE entity. Valid values: I - INDIVIDUAL,  C - CORPORATE',
    CORPORATE_NAME		varchar(250)	comment	'Corporate Name of the Insured.',
    PREM_AMT			double(12,2)	not null comment 'Premium amount of the CTPL cover.',
    TAX_AMT				double(12,2)	not null comment 'Total Amount for Taxes/Charges.',
	PREM_SEQ_NO			bigint(12)		comment 'Premium sequence number. Together with the issuing source, this will serve as unique identification of the bill.' unique,
	OR_NO				bigint(10)		comment 'System-generated Official Receipt number.' unique,
    LAST_UPDATE			datetime		not null comment 'Date when the record is last updated. This is system generated.',
    primary key (POLICY_ID)
);