version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo Installing serverless framework...
      - npm i -g serverless
  pre_build:
    commands:
      -
  build:
    commands:
      - echo Deployment started on `date`
      # put build details for lambda function here (call serverless template here)
      - serverless deploy
  post_build:
    commands:
      - echo Deployment done on `date`
