AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Layer for common functions used by E-Products

Resources:
  BlissCommons:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: eproducts-common
      Description: Layer containing MySQL utility and custom response builder modules
      CompatibleRuntimes:
        - nodejs8.10
        - nodejs10.x
      LicenseInfo: Available under the MIT license
      ContentUri: dependencies/

Outputs:
  EProductsCommonARN:
    Description: ARN of this layer (commons)
    Value: !Ref BlissCommons
    Export:
      Name: eproducts-common-arn
